<x-admin-layout title="Portfolio profile · bworiey">
    <div class="mb-8"><p class="text-sm text-[#7c7c6f]">{ Public profile }</p><h1 class="mt-2 font-display text-5xl font-semibold tracking-[-.08em]">Portfolio profile.</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-[#7c7c6f]">Data di halaman ini menjadi sumber profil utama pada homepage.</p></div>
    @if ($errors->any())<div class="mb-6 rounded-lg border border-red-400/40 bg-red-400/10 px-4 py-3 text-sm text-red-200"><ul class="list-disc space-y-1 pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('admin.portfolio-profile.update') }}" enctype="multipart/form-data" class="space-y-6">@csrf @method('PATCH')
        <section class="rounded-lg border border-[#42433d] bg-[#191919] p-5 sm:p-7"><h2 class="font-display text-2xl">Identity and story</h2><div class="mt-5 grid gap-5 md:grid-cols-2">@foreach ([['full_name','Nama lengkap'],['display_name','Nama tampil'],['professional_title','Judul profesional'],['short_bio','Bio singkat'],['hero_heading','Judul hero'],['hero_description','Deskripsi hero'],['email','Email'],['phone','Telepon'],['city','Kota'],['country','Negara'],['availability_status','Status availability'],['availability_text','Teks availability']] as [$name,$label])<label class="block text-sm text-[#7c7c6f]">{{ $label }}@if (in_array($name, ['short_bio','hero_description'], true))<textarea name="{{ $name }}" rows="3" class="admin-input mt-2">{{ old($name, $profile->{$name}) }}</textarea>@else<input name="{{ $name }}" value="{{ old($name, $profile->{$name}) }}" class="admin-input mt-2">@endif</label>@endforeach<label class="block text-sm text-[#7c7c6f] md:col-span-2">Bio lengkap<textarea name="full_bio" rows="6" class="admin-input mt-2">{{ old('full_bio', $profile->full_bio) }}</textarea></label></div></section>
        <section class="rounded-lg border border-[#42433d] bg-[#191919] p-5 sm:p-7"><h2 class="font-display text-2xl">Stats and media</h2><div class="mt-5 grid gap-5 md:grid-cols-3"><label class="block text-sm text-[#7c7c6f]">Tahun pengalaman<input type="number" min="0" name="years_experience" value="{{ old('years_experience', $profile->years_experience) }}" class="admin-input mt-2"></label><label class="block text-sm text-[#7c7c6f]">Project selesai<input type="number" min="0" name="projects_completed" value="{{ old('projects_completed', $profile->projects_completed) }}" class="admin-input mt-2"></label><label class="block text-sm text-[#7c7c6f]">Klien dilayani<input type="number" min="0" name="clients_served" value="{{ old('clients_served', $profile->clients_served) }}" class="admin-input mt-2"></label><label class="block text-sm text-[#7c7c6f]">Foto profil<input type="file" name="profile_image" accept="image/*" class="admin-input mt-2 p-2"></label><label class="block text-sm text-[#7c7c6f]">Foto about<input type="file" name="about_image" accept="image/*" class="admin-input mt-2 p-2"></label><label class="flex items-center gap-3 self-end text-sm"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $profile->is_active)) class="h-4 w-4 accent-[#abff84]">Tampilkan di publik</label></div></section>
        <div class="flex justify-end"><button class="rounded-full bg-[#abff84] px-6 py-3 text-sm font-semibold text-[#0e100f] transition hover:bg-[#fffce1]">Simpan profil</button></div>
    </form>
</x-admin-layout>
