<x-admin-layout title="Site settings · bworiey">
    <div class="mb-8"><p class="text-sm text-[#7c7c6f]">{ Control the public site }</p><h1 class="mt-2 font-display text-5xl font-semibold tracking-[-.08em]">Site settings.</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-[#7c7c6f]">Kelola identitas, SEO, tampilan, dan fitur publik tanpa mengubah kode.</p></div>
    @if ($errors->any())<div class="mb-6 rounded-lg border border-red-400/40 bg-red-400/10 px-4 py-3 text-sm text-red-200"><ul class="list-disc space-y-1 pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('admin.settings.update') }}" class="space-y-6">@csrf @method('PUT')
        <section class="rounded-lg border border-[#42433d] bg-[#191919] p-5 sm:p-7"><h2 class="font-display text-2xl">Identitas</h2><div class="mt-5 grid gap-5 md:grid-cols-2">@foreach ([['site_name','Nama site'],['studio_name','Nama brand'],['site_tagline','Tagline'],['site_description','Deskripsi']] as [$name,$label])<label class="block text-sm text-[#7c7c6f]">{{ $label }}<input name="{{ $name }}" value="{{ old($name, $settings[$name] ?? '') }}" class="admin-input mt-2" @if ($name === 'site_description') maxlength="500" @endif></label>@endforeach</div></section>
        <section class="rounded-lg border border-[#42433d] bg-[#191919] p-5 sm:p-7"><h2 class="font-display text-2xl">Hero dan kontak</h2><div class="mt-5 grid gap-5 md:grid-cols-2">@foreach ([['hero_badge','Label hero'],['hero_title','Judul hero'],['hero_subtitle','Subjudul hero'],['hero_description','Deskripsi hero'],['public_email','Email publik'],['business_email','Email bisnis'],['phone','Telepon'],['whatsapp','WhatsApp'],['city','Kota'],['country','Negara'],['availability_status','Status availability'],['availability_label','Label availability']] as [$name,$label])<label class="block text-sm text-[#7c7c6f]">{{ $label }}<input name="{{ $name }}" value="{{ old($name, $settings[$name] ?? '') }}" class="admin-input mt-2"></label>@endforeach</div></section>
        <section class="rounded-lg border border-[#42433d] bg-[#191919] p-5 sm:p-7"><h2 class="font-display text-2xl">SEO dan appearance</h2><div class="mt-5 grid gap-5 md:grid-cols-2"><label class="block text-sm text-[#7c7c6f]">Meta title<input name="default_meta_title" value="{{ old('default_meta_title', $settings['default_meta_title'] ?? '') }}" class="admin-input mt-2"></label><label class="block text-sm text-[#7c7c6f]">Canonical URL<input type="url" name="default_canonical_url" value="{{ old('default_canonical_url', $settings['default_canonical_url'] ?? '') }}" class="admin-input mt-2"></label><label class="block text-sm text-[#7c7c6f] md:col-span-2">Meta description<textarea name="default_meta_description" rows="3" class="admin-input mt-2">{{ old('default_meta_description', $settings['default_meta_description'] ?? '') }}</textarea></label><label class="block text-sm text-[#7c7c6f]">Tema default<select name="default_theme" class="admin-input mt-2"><option value="dark" @selected(old('default_theme', $settings['default_theme'] ?? 'dark') === 'dark')>Dark</option><option value="light" @selected(old('default_theme', $settings['default_theme'] ?? 'dark') === 'light')>Light</option></select></label><label class="block text-sm text-[#7c7c6f]">Bahasa default<select name="default_language" class="admin-input mt-2"><option value="id" @selected(old('default_language', $settings['default_language'] ?? 'id') === 'id')>Indonesia</option><option value="en" @selected(old('default_language', $settings['default_language'] ?? 'id') === 'en')>English</option></select></label></div></section>
        <section class="rounded-lg border border-[#42433d] bg-[#191919] p-5 sm:p-7"><h2 class="font-display text-2xl">Fitur publik</h2><div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach (['show_theme_switcher'=>'Theme switcher','show_language_switcher'=>'Language switcher','contact_form_enabled'=>'Contact form','blog_enabled'=>'Blog','testimonials_enabled'=>'Testimonials','services_enabled'=>'Services','analytics_enabled'=>'Analytics','registration_enabled'=>'Registration','maintenance_mode'=>'Maintenance mode'] as $name => $label)<label class="flex items-center gap-3 text-sm"><input type="hidden" name="{{ $name }}" value="0"><input type="checkbox" name="{{ $name }}" value="1" @checked(old($name, $settings[$name] ?? false)) class="h-4 w-4 accent-[#abff84]">{{ $label }}</label>@endforeach</div></section>
        <div class="flex justify-end"><button class="rounded-full bg-[#abff84] px-6 py-3 text-sm font-semibold text-[#0e100f] transition hover:bg-[#fffce1]">Simpan pengaturan</button></div>
    </form>
</x-admin-layout>
