<x-admin-layout :title="($mode === 'create' ? 'Add user' : 'Edit user').' · bworiey'">
    <div class="mb-8"><a href="{{ route('admin.users.index') }}" class="text-sm text-[#abff84]">← Back to users</a><p class="mb-3 mt-8 text-sm text-[#7c7c6f]">{ {{ $mode === 'create' ? 'New account' : 'Account details' }} }</p><h1 class="font-display text-5xl tracking-[-.08em]">{{ $mode === 'create' ? 'Add user' : 'Edit user' }}</h1></div>
    @if($errors->any())<div class="mb-6 rounded-lg border border-[#fca5a5]/50 bg-[#fca5a5]/10 p-4 text-sm text-[#fecaca]"><ul class="list-inside list-disc space-y-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" enctype="multipart/form-data" action="{{ $mode === 'create' ? route('admin.users.store') : route('admin.users.update', $user) }}" class="grid max-w-4xl gap-6">@csrf @if($mode === 'edit') @method('PUT') @endif
        <div class="grid gap-6 rounded-lg border border-[#42433d] bg-[#191919] p-6 md:grid-cols-2"><label class="grid gap-2 text-sm text-[#7c7c6f]">Name<input name="name" value="{{ old('name', $user->name) }}" required class="rounded-md border-[#42433d] bg-[#0e100f] text-[#fffce1] focus:border-[#abff84] focus:ring-[#abff84]"></label><label class="grid gap-2 text-sm text-[#7c7c6f]">Email<input type="email" name="email" value="{{ old('email', $user->email) }}" required class="rounded-md border-[#42433d] bg-[#0e100f] text-[#fffce1] focus:border-[#abff84] focus:ring-[#abff84]"></label><label class="grid gap-2 text-sm text-[#7c7c6f]">Password{{ $mode === 'edit' ? ' (optional)' : '' }}<input type="password" name="password" {{ $mode === 'create' ? 'required' : '' }} autocomplete="new-password" class="rounded-md border-[#42433d] bg-[#0e100f] text-[#fffce1] focus:border-[#abff84] focus:ring-[#abff84]"></label><label class="grid gap-2 text-sm text-[#7c7c6f]">Confirm password<input type="password" name="password_confirmation" {{ $mode === 'create' ? 'required' : '' }} autocomplete="new-password" class="rounded-md border-[#42433d] bg-[#0e100f] text-[#fffce1] focus:border-[#abff84] focus:ring-[#abff84]"></label><label class="grid gap-2 text-sm text-[#7c7c6f]">Status<select name="status" class="rounded-md border-[#42433d] bg-[#0e100f] text-[#fffce1] focus:border-[#abff84] focus:ring-[#abff84]">@foreach(\App\Enums\UserStatus::cases() as $status)<option value="{{ $status->value }}" @selected(old('status', $user->status?->value) === $status->value)>{{ $status->label() }}</option>@endforeach</select></label><label class="grid gap-2 text-sm text-[#7c7c6f]">Avatar<input type="file" name="avatar" accept="image/jpeg,image/png,image/webp" class="rounded-md border-[#42433d] bg-[#0e100f] text-sm text-[#7c7c6f] file:mr-4 file:border-0 file:bg-[#fffce1] file:px-3 file:py-2 file:text-[#0e100f]"></label></div>
        <div class="rounded-lg border border-[#42433d] bg-[#191919] p-6"><h2 class="text-sm font-medium">Roles</h2><p class="mt-1 text-xs text-[#7c7c6f]">Role is the primary source of access. Super Admin assignment is protected server-side.</p><div class="mt-5 grid gap-3 sm:grid-cols-2">@php($selectedRoles = old('roles', $user->roles?->pluck('name')->all() ?? []))@foreach($roles as $role)<label class="flex items-center gap-3 rounded-md border border-[#42433d] p-3 text-sm transition hover:border-[#7c7c6f]"><input type="checkbox" name="roles[]" value="{{ $role->name }}" @checked(in_array($role->name, $selectedRoles, true)) class="rounded border-[#42433d] bg-[#0e100f] text-[#abff84] focus:ring-[#abff84]"><span>{{ $role->name }}</span>@if(in_array($role->name, config('portfolio.system_roles'), true))<span class="ml-auto text-[10px] uppercase tracking-[.12em] text-[#7c7c6f]">System</span>@endif</label>@endforeach</div></div>
        <div class="flex gap-3"><button class="rounded-full border border-[#abff84] px-5 py-3 text-sm font-medium text-[#abff84] transition hover:bg-[#abff84] hover:text-[#0e100f]">Save user ↗</button><a href="{{ route('admin.users.index') }}" class="rounded-full border border-[#42433d] px-5 py-3 text-sm text-[#7c7c6f] transition hover:text-[#fffce1]">Cancel</a></div>
    </form>
</x-admin-layout>
