<x-admin-layout title="Users · bworiey">
    <div class="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="mb-3 text-sm text-[#7c7c6f]">{ Access control }</p><h1 class="font-display text-5xl tracking-[-.08em] sm:text-6xl">Users</h1></div>@can('users.create')<a href="{{ route('admin.users.create') }}" class="rounded-full border border-[#fffce1] px-5 py-3 text-sm font-medium transition hover:bg-[#fffce1] hover:text-[#0e100f]">Add user <span aria-hidden="true">↗</span></a>@endcan</div>
    <form method="GET" class="mb-5 grid gap-3 rounded-lg border border-[#42433d] bg-[#191919] p-4 md:grid-cols-[1fr_170px_170px_auto]">
        <label class="sr-only" for="search">Search users</label><input id="search" name="search" value="{{ request('search') }}" placeholder="Search name or email" class="rounded-md border-[#42433d] bg-[#0e100f] text-sm text-[#fffce1] placeholder:text-[#7c7c6f] focus:border-[#abff84] focus:ring-[#abff84]">
        <select name="role" class="rounded-md border-[#42433d] bg-[#0e100f] text-sm text-[#fffce1] focus:border-[#abff84] focus:ring-[#abff84]"><option value="">All roles</option>@foreach($roles as $role)<option value="{{ $role->name }}" @selected(request('role') === $role->name)>{{ $role->name }}</option>@endforeach</select>
        <select name="status" class="rounded-md border-[#42433d] bg-[#0e100f] text-sm text-[#fffce1] focus:border-[#abff84] focus:ring-[#abff84]"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select>
        <button class="rounded-md border border-[#fffce1] px-4 py-2 text-sm transition hover:bg-[#fffce1] hover:text-[#0e100f]">Filter</button>
    </form>
    <div class="overflow-hidden rounded-lg border border-[#42433d] bg-[#191919]"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-[#42433d] text-left text-sm"><thead class="text-xs uppercase tracking-[.14em] text-[#7c7c6f]"><tr><th class="px-5 py-4 font-normal">User</th><th class="px-5 py-4 font-normal">Role</th><th class="px-5 py-4 font-normal">Status</th><th class="px-5 py-4 font-normal">Last login</th><th class="px-5 py-4 font-normal">Actions</th></tr></thead><tbody class="divide-y divide-[#42433d]">
        @forelse($users as $user)<tr class="align-middle"><td class="whitespace-nowrap px-5 py-4"><div class="flex items-center gap-3"><img src="{{ $user->avatar_url }}" alt="" class="h-9 w-9 rounded-full object-cover"><div><a href="{{ route('admin.users.show', $user) }}" class="font-medium hover:text-[#abff84]">{{ $user->name }}</a><p class="text-xs text-[#7c7c6f]">{{ $user->email }}</p></div></div></td><td class="px-5 py-4 text-xs text-[#7c7c6f]">{{ $user->roles->pluck('name')->join(', ') ?: 'No role' }}</td><td class="px-5 py-4"><span class="rounded-full border px-2.5 py-1 text-xs {{ $user->isActive() ? 'border-[#0ae448]/40 text-[#abff84]' : 'border-[#ff8709]/40 text-[#ffb85c]' }}">{{ $user->status?->label() }}</span>@if($user->trashed()) <span class="ml-1 text-xs text-[#fca5a5]">Deleted</span>@endif</td><td class="whitespace-nowrap px-5 py-4 text-xs text-[#7c7c6f]">{{ $user->last_login_at?->diffForHumans() ?? 'Never' }}</td><td class="px-5 py-4"><div class="flex items-center gap-3 text-xs"><a href="{{ route('admin.users.show', $user) }}" class="text-[#abff84] hover:underline">View</a>@if(!$user->trashed()) @can('update', $user)<a href="{{ route('admin.users.edit', $user) }}" class="text-[#7c7c6f] hover:text-[#fffce1]">Edit</a>@endcan @can('delete', $user)<form method="POST" action="{{ route('admin.users.destroy', $user) }}" onsubmit="return confirm('Move this user to trash?')">@csrf @method('DELETE')<button class="text-[#fca5a5]">Delete</button></form>@endcan @else @can('restore', $user)<form method="POST" action="{{ route('admin.users.restore', $user->id) }}">@csrf<button class="text-[#abff84]">Restore</button></form>@endcan @endif</div></td></tr>@empty<tr><td colspan="5" class="px-5 py-16 text-center text-sm text-[#7c7c6f]">No users match these filters.</td></tr>@endforelse
    </tbody></table></div><div class="border-t border-[#42433d] px-5 py-4">{{ $users->links() }}</div></div>
</x-admin-layout>
